const defaults={title:"Payment Methods",nepalMin:"Rs. 1,000 NPR",internationalMin:"$20 USD/USDT",time:"30 minutes",screenshotInstruction:"Take the screenshot of Successful payment and upload it below",contactMessage:"Please send same screenshot on message to verify, I will know you are waiting and contact you as soon as possible, Please Don't panic you are in queue",whatsappName:"DARWIN NIROULA",whatsappUsername:"ndarwin1414",whatsappPhone:"+9779842723995",nepal:[{id:"nabil",name:"Nabil Bank Limited",short:"NB",logo:"",qr:"",details:[["Account Holder","DARWIN NIROULA"],["Account Number","09810017535771"],["SWIFT","NARBNPKA"]]},{id:"esewa",name:"eSewa",short:"eS",logo:"",qr:"",details:[["ID Owner","DARWIN NIROULA"],["eSewa ID","+9779842723995"],["Username","ndarwin1414"]]}],international:[{id:"trc20",name:"USDT – TRC20 (Tron)",short:"₮",logo:"",qr:"",details:[["Network","TRC20 (Tron)"],["Wallet Address","TH4guJP4iXEpxTZwgdz4NzenSv7DH3oVzW"],["Holder","DARWIN NIROULA"]]},{id:"bep20",name:"USDT – BEP20 (Binance Smart Chain)",short:"₮",logo:"",qr:"",details:[["Network","BEP20 (Binance Smart Chain)"],["Wallet Address","0x5ef45b836e6005ce6f5ed7c2aee8d235a104fc76"],["Holder","DARWIN NIROULA"]]},{id:"erc20",name:"USDT – ERC20 (Ethereum)",short:"₮",logo:"",qr:"",details:[["Network","ERC20 (Ethereum)"],["Wallet Address","0x5ef45b836e6005ce6f5ed7c2aee8d235a104fc76"],["Holder","DARWIN NIROULA"]]},{id:"neteller",name:"NETELLER",short:"N",logo:"",qr:"",details:[["NETELLER ID","363887821"],["Holder","DARWIN NIROULA"]]},{id:"skrill",name:"SKRILL",short:"S",logo:"",qr:"",details:[["SKRILL ID","241971338"],["Holder","DARWIN NIROULA"]]},{id:"payoneer",name:"PAYONEER",short:"P",logo:"",qr:"",details:[["PAYONEER ID","76121661"],["Holder","DARWIN NIROULA"]]}]};
let cfg=defaults,selected=null;const app=document.getElementById("app");const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[m]));
async function load(){try{const r=await fetch("/api/config",{cache:"no-store"});if(r.ok)cfg=await r.json()}catch{}}
function logo(m){return m.logo?'<img src="'+esc(m.logo)+'" alt="'+esc(m.name)+' logo">':'<span class="logo-fallback">'+esc(m.short||m.name.slice(0,2))+'</span>'}
function card(m){return '<article class="method-card"><div class="logo-wrap">'+logo(m)+'</div><div class="method-name">'+esc(m.name)+'</div><button class="pay-btn" onclick="openPayment(\''+m.id+'\')">Pay</button></article>'}
function home(){app.innerHTML='<div class="page">'+(cfg.logo?'<div class="portal-logo"><img src="'+esc(cfg.logo)+'" alt="Logo"></div>':'')+'<h1 class="title">Payment Methods</h1>'<section class="section"><h2 class="section-title">1. Nepal Payment (नेपाल)</h2><div class="method-list">'+cfg.nepal.map(card).join("")+'</div></section><section class="section"><h2 class="section-title">2. International Payment</h2><div class="method-list">'+cfg.international.map(card).join("")+'</div></section><a class="admin-link" href="#admin">Owner editor</a></div>'}
function find(id){return [...cfg.nepal,...cfg.international].find(x=>x.id===id)}
function openPayment(id){selected=find(id);history.pushState({}, "", "#payment");payment()}
function payment(){if(!selected)return home();const np=cfg.nepal.some(x=>x.id===selected.id);app.innerHTML='<div class="page"><div class="topbar"><button class="back" onclick="goHome()">← Payment Methods</button><span></span></div><div class="info-card"><div class="payment-heading"><h2>'+(np?"Nepal Payment":"International Payment")+'</h2><p>Minimum = '+esc(np?cfg.nepalMin:cfg.internationalMin)+'</p><p>Time :- '+esc(cfg.time)+'</p></div><h3 class="section-title">'+esc(selected.name)+'</h3><div class="detail-list">'+selected.details.map((d,i)=>'<div class="detail-row"><div class="detail-label">'+esc(d[0])+'</div><div class="detail-main"><div class="detail-value">'+esc(d[1])+'</div><button class="copy-btn" onclick="copyDetail(this,'+i+')">Copy</button></div></div>').join("")+'</div>'+(selected.qr?'<div class="qr-section"><div class="qr-box"><img id="qrImage" src="'+esc(selected.qr)+'" alt="QR code"></div><div class="qr-controls"><button type="button" onclick="adjustQR(-1)">−</button><span id="qrZoom">100%</span><button type="button" onclick="adjustQR(1)">+</button></div></div>':'<div class="qr-section"><div class="qr-box"><div class="qr-placeholder">QR code area — add the method\'s QR in the owner editor.</div></div></div>')+'<p class="instruction">'+esc(cfg.screenshotInstruction)+'</p><div class="upload-wrap"><label id="uploadLabel" class="upload-label"><span id="uploadPrompt">Upload Payment Screenshot Here</span><input id="proof" type="file" accept="image/*" onchange="unlock(this)"></label><button id="contactBtn" class="contact-btn disabled" disabled>Contact Details</button></div></div></div>'}
async function copyDetail(btn,i){const v=selected.details[i][1];try{await navigator.clipboard.writeText(v)}catch{const t=document.createElement("textarea");t.value=v;document.body.appendChild(t);t.select();document.execCommand("copy");t.remove()}btn.textContent="✅ Copied";setTimeout(()=>btn.textContent="Copy",1200)}
function unlock(input){if(!input.files?.length)return;const file=input.files[0];if(!file.type.startsWith("image/")){input.value="";return}const url=URL.createObjectURL(file),label=document.getElementById("uploadLabel"),prompt=document.getElementById("uploadPrompt"),b=document.getElementById("contactBtn"),preview=new Image();preview.className="screenshot-preview";preview.alt="Selected payment screenshot";preview.onload=()=>{label.classList.add("has-preview");prompt.style.display="none";label.appendChild(preview);b.disabled=false;b.className="contact-btn enabled";b.onclick=()=>{history.pushState({}, "", "#contact");contact()};input.value="";URL.revokeObjectURL(url)};preview.onerror=()=>{input.value="";URL.revokeObjectURL(url)};preview.src=url}
function adjustQR(direction){const img=document.getElementById("qrImage"),label=document.getElementById("qrZoom");if(!img||!label)return;let z=parseInt(label.textContent)||100;z=Math.max(50,Math.min(150,z+direction*10));img.style.width=z+"%";label.textContent=z+"%"}
function contact(){app.innerHTML='<div class="page"><div class="topbar"><button class="back" onclick="goHome()">← Payment Methods</button><span></span></div><div class="contact-note">'+esc(cfg.contactMessage)+'</div><div class="whatsapp-card"><div class="whatsapp-logo"><svg viewBox="0 0 32 32"><path d="M16 3C8.8 3 3 8.8 3 16c0 2.3.6 4.5 1.7 6.5L3 29l6.7-1.6A13 13 0 1 0 16 3Zm0 23.5c-2 0-4-.5-5.8-1.6l-.4-.2-4 .9 1-3.8-.3-.4A10.5 10.5 0 1 1 16 26.5Zm5.8-7.9c-.3-.2-1.9-.9-2.2-1.1-.3-.2-.5-.2-.7.2l-1 1.2c-.2.2-.4.3-.7.1-.3-.2-1.3-.5-2.6-1.6-1-.9-1.6-1.9-1.8-2.2-.2-.3 0-.5.1-.7l.5-.6c.2-.2.2-.3.3-.5.1-.2 0-.4 0-.6l-1-2.4c-.3-.7-.5-.6-.7-.6h-.6c-.2 0-.6.1-.9.4-.3.3-1.1 1.1-1.1 2.7s1.2 3.1 1.3 3.4c.2.2 2.3 3.5 5.6 4.9.8.3 1.4.5 2.1.1.6-.1 1.9-.8 2.2-1.5.3-.8.3-1.4.2-1.5-.1-.1-.3-.2-.6-.4Z"/></svg></div><div class="whatsapp-brand">WhatsApp</div><h2 class="contact-name">'+esc(cfg.whatsappName)+'</h2><p class="contact-line">Username: '+esc(cfg.whatsappUsername)+'</p><p class="contact-line">'+esc(cfg.whatsappPhone)+'</p><button class="direct-btn" onclick="whatsapp()">Direct Message</button></div></div>'}
function whatsapp(){location.href="https://wa.me/"+cfg.whatsappPhone.replace(/\D/g,"")}
function goHome(){history.pushState({}, "", "#");home()}
function field(k,label,area=false){return '<div class="editor-row"><label style="width:150px;font-weight:700;font-size:13px">'+label+'</label>'+(area?'<textarea id="f-'+k+'">'+esc(cfg[k])+'</textarea>':'<input id="f-'+k+'" value="'+esc(cfg[k])+'">')+'</div>'}
function adminSection(title,arr){return '<div class="editor-card"><h2 class="section-title">'+title+'</h2>'+arr.map(m=>'<div class="editor-card" style="box-shadow:none;background:#fafcfa"><div class="editor-row"><input id="n-'+m.id+'" value="'+esc(m.name)+'"><button class="small-btn" onclick="del(\''+m.id+'\')">Delete</button></div><div class="editor-row"><input id="l-'+m.id+'" value="'+esc(m.logo)+'" placeholder="Official logo asset URL/path"></div>'+m.details.map((d,i)=>'<div class="editor-row"><input id="dl-'+m.id+'-'+i+'" value="'+esc(d[0])+'" style="max-width:35%"><input id="dv-'+m.id+'-'+i+'" value="'+esc(d[1])+'"></div>').join("")+'<div class="editor-row"><input id="q-'+m.id+'" value="'+esc(m.qr)+'" placeholder="QR image URL/path"></div></div>').join("")+'</div>'}
async function admin(){const r=await fetch("/api/me",{cache:"no-store"}).catch(()=>null);if(!r||!(await r.json()).ok){login();return}app.innerHTML='<div class="admin"><div class="topbar"><button class="back" onclick="goHome()">← Customer page</button><button class="small-btn" onclick="logout()">Log out</button></div><h1 class="title">Owner Editor</h1><div class="notice">Central owner configuration is protected by the server. Customer payment screenshots are never uploaded, saved, inspected, or sent by this portal.</div><div class="editor-card"><h2 class="section-title">General</h2>'+field("nepalMin","Nepal minimum")+field("internationalMin","International minimum")+field("time","Time")+field("screenshotInstruction","Screenshot instruction")+field("contactMessage","Contact message",true)+field("whatsappName","WhatsApp name")+field("whatsappUsername","WhatsApp username")+field("whatsappPhone","WhatsApp phone")+'</div>'+adminSection("Nepal",cfg.nepal)+adminSection("International",cfg.international)+'<button class="save-btn" onclick="save()">Save configuration</button></div>'}
function login(){app.innerHTML='<div class="admin"><h1 class="title">Owner Login</h1><div class="editor-card"><div class="notice">Owner access is protected by a server-side password. No password is stored in this page.</div><form onsubmit="return doLogin(event)"><div class="editor-row"><label style="width:150px;font-weight:700;font-size:13px">Password</label><input id="adminPassword" type="password" autocomplete="current-password" required></div><button class="save-btn" type="submit">Sign in</button><p id="loginError" class="notice" style="display:none"></p></form></div><button class="back" onclick="goHome()">← Customer page</button></div>'}
async function doLogin(e){e.preventDefault();const p=document.getElementById("adminPassword").value;const r=await fetch("/api/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:p})});if(!r.ok){const x=document.getElementById("loginError");x.textContent="Invalid password.";x.style.display="block";return false}await load();admin();return false}
async function logout(){await fetch("/api/logout",{method:"POST"});goHome()}
function del(id){cfg.nepal=cfg.nepal.filter(x=>x.id!==id);cfg.international=cfg.international.filter(x=>x.id!==id);admin()}
async function save(){["nepalMin","internationalMin","time","screenshotInstruction","contactMessage","whatsappName","whatsappUsername","whatsappPhone"].forEach(k=>{const e=document.getElementById("f-"+k);if(e)cfg[k]=e.value});[...cfg.nepal,...cfg.international].forEach(m=>{const n=document.getElementById("n-"+m.id),l=document.getElementById("l-"+m.id),q=document.getElementById("q-"+m.id);if(n)m.name=n.value;if(l)m.logo=l.value;if(q)m.qr=q.value;m.details.forEach((d,i)=>{d[0]=document.getElementById("dl-"+m.id+"-"+i).value;d[1]=document.getElementById("dv-"+m.id+"-"+i).value})});const r=await fetch("/api/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(cfg)});if(!r.ok){alert("Save failed: "+(await r.text()));return}home()}
window.__portalState=()=>({cfg:()=>cfg,setCfg:v=>{cfg=v},app:()=>app,find,allMethods,home,reload:load});
window.addEventListener("popstate",()=>location.hash==="#admin"?admin():location.hash==="#contact"?contact():home());
Object.assign(window,{openPayment,copyDetail,unlock,adjustQR,goHome,whatsapp,admin,save,del,doLogin,logout});
(async()=>{await load();if(location.hash==="#admin")admin();else if(location.hash==="#contact")contact();else home()})();