const DEFAULT_CONFIG={title:"Payment Methods",nepalMin:"Rs. 1,000 NPR",internationalMin:"$20 USD/USDT",time:"30 minutes",screenshotInstruction:"Take the screenshot of Successful payment and upload it below",contactMessage:"Please send same screenshot on message to verify, I will know you are waiting and contact you as soon as possible, Please Don't panic you are in queue",whatsappName:"DARWIN NIROULA",whatsappUsername:"ndarwin1414",whatsappPhone:"+9779842723995",nepal:[{id:"nabil",name:"Nabil Bank Limited",short:"NB",logo:"",qr:"",details:[["Account Holder","DARWIN NIROULA"],["Account Number","09810017535771"],["SWIFT","NARBNPKA"]]},{id:"esewa",name:"eSewa",short:"eS",logo:"",qr:"",details:[["ID Owner","DARWIN NIROULA"],["eSewa ID","+9779842723995"],["Username","ndarwin1414"]]}],international:[{id:"trc20",name:"USDT – TRC20 (Tron)",short:"₮",logo:"",qr:"",details:[["Network","TRC20 (Tron)"],["Wallet Address","TH4guJP4iXEpxTZwgdz4NzenSv7DH3oVzW"],["Holder","DARWIN NIROULA"]]},{id:"bep20",name:"USDT – BEP20 (Binance Smart Chain)",short:"₮",logo:"",qr:"",details:[["Network","BEP20 (Binance Smart Chain)"],["Wallet Address","0x5ef45b836e6005ce6f5ed7c2aee8d235a104fc76"],["Holder","DARWIN NIROULA"]]},{id:"erc20",name:"USDT – ERC20 (Ethereum)",short:"₮",logo:"",qr:"",details:[["Network","ERC20 (Ethereum)"],["Wallet Address","0x5ef45b836e6005ce6f5ed7c2aee8d235a104fc76"],["Holder","DARWIN NIROULA"]]},{id:"neteller",name:"NETELLER",short:"N",logo:"",qr:"",details:[["NETELLER ID","363887821"],["Holder","DARWIN NIROULA"]]},{id:"skrill",name:"SKRILL",short:"S",logo:"",qr:"",details:[["SKRILL ID","241971338"],["Holder","DARWIN NIROULA"]]},{id:"payoneer",name:"PAYONEER",short:"P",logo:"",qr:"",details:[["PAYONEER ID","76121661"],["Holder","DARWIN NIROULA"]]}]};
const enc=new TextEncoder();
function b64u(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
function unb64u(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const x=atob(s);return Uint8Array.from(x,c=>c.charCodeAt(0))}
async function sign(secret,data){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(data)))}
async function sessionToken(secret){const ts=Date.now().toString();return ts+"."+b64u(await sign(secret,ts))}
async function authorized(request,secret){if(!secret)return false;const c=request.headers.get("Cookie")||"",m=c.match(/dp_admin=([^;]+)/);if(!m)return false;const p=m[1].split(".");if(p.length!==2)return false;const ts=Number(p[0]);if(!Number.isFinite(ts)||Date.now()-ts>43200000||Date.now()<ts)return false;const expected=await sign(secret,p[0]),got=unb64u(p[1]);if(got.length!==expected.length)return false;let d=0;for(let i=0;i<got.length;i++)d|=got[i]^expected[i];return d===0}
async function getConfig(env){if(env.PAYMENT_CONFIG){const v=await env.PAYMENT_CONFIG.get("config","json");if(v)return v}return DEFAULT_CONFIG}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/api/config"&&request.method==="GET")return json(await getConfig(env));if(url.pathname==="/api/login"&&request.method==="POST"){const body=await request.json().catch(()=>({})),secret=env.ADMIN_PASSWORD||"";if(!secret||body.password!==secret)return json({ok:false,error:"Invalid password"},401);const token=await sessionToken(secret);return new Response(JSON.stringify({ok:true}),{headers:{"content-type":"application/json","cache-control":"no-store","set-cookie":"dp_admin="+token+"; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200"}})}if(url.pathname==="/api/me"&&request.method==="GET")return json({ok:await authorized(request,env.ADMIN_PASSWORD||"")});if(url.pathname==="/api/logout"&&request.method==="POST")return new Response(JSON.stringify({ok:true}),{headers:{"content-type":"application/json","set-cookie":"dp_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0"}});if(url.pathname==="/api/config"&&request.method==="PUT"){if(!(await authorized(request,env.ADMIN_PASSWORD||"")))return json({ok:false,error:"Unauthorized"},401);if(!env.PAYMENT_CONFIG)return json({ok:false,error:"PAYMENT_CONFIG KV binding is not configured"},503);const cfg=await request.json();await env.PAYMENT_CONFIG.put("config",JSON.stringify(cfg));return json({ok:true})}return env.ASSETS.fetch(request)}};
